#!/usr/bin/env python3
# Generator for examples/prove/poseidon2_node.glass — the REAL Plonky3 Poseidon2 permutation
# (Goldilocks t=12, R_F=8, R_P=22, x^7) expressed as a provable Glass circuit (H3 block B2). The bridge
# lowers plain-Int arithmetic to Goldilocks field gates, but Glass `Int` is int64 and Poseidon2's round
# constants are ~2^64, so each constant is emitted as `hi*4294967296 + lo` (the circuit reduces mod p at
# every gate; the reference interpreter int64-overflows -> circuit-faithful, like merkle_member). The
# 12-lane state is threaded through 31 layers via round-functions returning 12-tuples (shallow, avoids
# deep-let clang overflow). Validated by fuzz/poseidon2_node_check.py against pentecost/poseidon.py's
# independent `perm`.  Regenerate:  python3 fuzz/gen_poseidon2_node.py > examples/prove/poseidon2_node.glass
import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from pentecost._gold_constants import RC_EI, RC_EF, RC_IN, DIAG

M4 = [[2, 3, 1, 1], [1, 2, 3, 1], [1, 1, 2, 3], [3, 1, 1, 2]]
def k(c): return f"({c // 4294967296} * 4294967296 + {c % 4294967296})"   # a ~2^64 constant as hi*2^32+lo
L = [f"l{i}" for i in range(12)]

def tup(names): return "(" + ", ".join(names) + ")"
def itype(n): return "(" + ", ".join(["Int"] * n) + ")"

out = []
out.append("# THE REAL Poseidon2 permutation (Plonky3 Goldilocks, t=12, R_F=8, R_P=22, x^7) as a provable")
out.append("# circuit — H3 building block B2. GENERATED by fuzz/gen_poseidon2_node.py from the published")
out.append("# constants (pentecost/_gold_constants.py); validated against pentecost/poseidon.py by")
out.append("# fuzz/poseidon2_node_check.py. Unlike merkle_member.glass's reduced toy hash, this is the FULL")
out.append("# production permutation: every round constant (a ~2^64 Goldilocks element, emitted as")
out.append("# hi*2^32+lo since Glass Int is int64) and both real linear layers (external M_E = 4x4 MDS per")
out.append("# chunk + cross-chunk column sums; internal M_I = diag*x + sum). The bridge lowers it to ~1.9k")
out.append("# field gates. The result is the 12 permuted lanes for input lanes 0..11.")
out.append("#")
out.append("#   glass prove examples/prove/poseidon2_node.glass i0=0 i1=1 i2=2 i3=3 i4=4 i5=5 i6=6 i7=7 i8=8 i9=9 i10=10 i11=11")
out.append("#")
out.append("# Circuit-faithful, NOT witness3-agreeing (the x^7 chains + ~2^64 constants overflow int64 in the")
out.append("# reference interpreter; the circuit reduces mod p). Cross-checked instead against the from-scratch")
out.append("# Python Poseidon2 (pentecost/poseidon.py) -- a stronger, independent oracle than the int64 interp.")
out.append("fn sb(x: Int) : Int = let x2 : Int = x * x in let x4 : Int = x2 * x2 in let x3 : Int = x * x2 in x3 * x4")
# --- external linear layer M_E ---
me = [f"fn mext({', '.join(n + ': Int' for n in L)}) : {itype(12)} ="]
lets = []
for c in range(3):                       # M4 on each 4-lane chunk
    for r in range(4):
        terms = " + ".join(f"{M4[r][kk]} * l{4*c+kk}" for kk in range(4))
        lets.append(f"  let ch{c}{r} : Int = {terms} in")
for m in range(4):                        # per-position column sums across the 3 chunks
    lets.append(f"  let cs{m} : Int = ch0{m} + ch1{m} + ch2{m} in")
newlanes = [f"ch{i//4}{i%4} + cs{i%4}" for i in range(12)]
me.append("\n".join(lets))
me.append("  (" + ", ".join(newlanes) + ")")
out.append("\n".join(me))
# --- internal linear layer M_I ---
mi = [f"fn mint({', '.join(n + ': Int' for n in L)}) : {itype(12)} ="]
mi.append("  let s : Int = " + " + ".join(L) + " in")
mi.append("  (" + ", ".join(f"{k(DIAG[i])} * l{i} + s" for i in range(12)) + ")")
out.append("\n".join(mi))

# --- the permutation: bare M_E, 4 external (RC_EI), 22 internal (RC_IN), 4 external (RC_EF) ---
perm = [f"fn perm({', '.join(f'i{i}: Int' for i in range(12))}) : {itype(12)} ="]
def vs(layer): return [f"v{layer}_{i}" for i in range(12)]
opens = []
# layer 0: bare external pre-multiply
opens.append(f"  match mext({', '.join(f'i{i}' for i in range(12))}) {{ {tup(vs(0))} =>")
layer = 0
def eround(prev, rc):                     # add RC, sbox all 12, then M_E
    args = ", ".join(f"sb({prev[i]} + {k(rc[i])})" for i in range(12))
    return f"mext({args})"
def iround(prev, rc):                     # add RC to lane 0, sbox lane 0, then M_I
    args = ", ".join([f"sb({prev[0]} + {k(rc)})"] + prev[1:])
    return f"mint({args})"
for r in range(4):                        # 4 external-initial rounds
    opens.append(f"  match {eround(vs(layer), RC_EI[r])} {{ {tup(vs(layer+1))} =>"); layer += 1
for r in range(22):                       # 22 internal rounds
    opens.append(f"  match {iround(vs(layer), RC_IN[r])} {{ {tup(vs(layer+1))} =>"); layer += 1
for r in range(4):                        # 4 external-final rounds
    opens.append(f"  match {eround(vs(layer), RC_EF[r])} {{ {tup(vs(layer+1))} =>"); layer += 1
perm.append("\n".join(opens))
perm.append("  " + tup(vs(layer)) + " " + "}" * (layer + 1))   # layer+1 matches opened (bare + 30 rounds)
out.append("\n".join(perm))

out.append(f"perm({', '.join(f'i{i}' for i in range(12))})")
sys.stdout.write("\n".join(out) + "\n")
