#!/usr/bin/env python3
# Regenerate the committed proof corpus (pentecost/corpus/*.b3.txt.gz) with the CURRENT emitter,
# verifying each fixture with the INDEPENDENT Pentecost verifier BEFORE it is committed.
#
#   python3 fuzz/regen_corpus.py
#
# Why this exists (v5.122.0): the corpus fixtures are the static differential/tamper coverage the
# suite runs (fuzz/corpus_check.py). They were previously regenerated BY HAND after any proof-format
# change — a "green-but-broken" vector: a contributor could emit fixtures with a new (broken) emitter
# and a matching (broken) parser, and the suite (which only PARSES the committed fixtures) would stay
# green even though the format silently changed. This script closes that gap: it emits each shape with
# the real `glass prove --emit`, then immediately runs `glass verify` (Pentecost, the independent
# verifier) and REFUSES to write the fixture unless Pentecost ACCEPTs. A consistent-wrong emit/parse
# pair still has to survive pentecost/difftest.sh (a live native emit -> parse round-trip) and the
# Stage-0 "old fixtures REJECT under the new parser" check — see docs/proof-size-frontier.md.
#
# Each shape's source + inputs match the showcase the fixture name maps to, so the corpus keeps
# spanning the prover's shapes: scalar arithmetic, comparison (range gadget), division, a record,
# a string-equality predicate, and a string-VALUED result.
import sys, os, gzip, subprocess, tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GLASS = os.path.join(ROOT, "glass.py")
CORPUS = os.path.join(ROOT, "pentecost", "corpus")
PY = sys.executable

# (fixture name, source: an expr string OR an examples/prove/*.glass path, {input: value})
SHAPES = [
    ("honest_a_plus_b",      "a + b",                               {"a": "3",  "b": "5"}),
    ("honest_a_times_b",     "a * b",                               {"a": "3",  "b": "5"}),
    ("honest_a_sq_plus_b",   "a * a + b",                           {"a": "3",  "b": "5"}),
    ("honest_a_lt_b",        "a < b",                               {"a": "3",  "b": "5"}),
    ("honest_a_div_b",       "a / b",                               {"a": "17", "b": "5"}),
    ("honest_record",        "examples/prove/record_stats.glass",   {"x": "3",  "y": "8"}),
    ("honest_str_eq",        "examples/prove/string_eq.glass",      {}),
    ("honest_string_result", "examples/prove/reveal_prefix.glass",  {"key": "sk-live-9f3a2c7e1b"}),
]

PROVE_TIMEOUT = 900  # the comparison/division gadgets are the slow ones (~600k-token proofs)


def source_path(src, tmpdir):
    """An expr like 'a + b' is written to a temp .glass; a path is used as-is."""
    if src.endswith(".glass"):
        return os.path.join(ROOT, src)
    p = os.path.join(tmpdir, "src.glass")
    open(p, "w").write(src + "\n")
    return p


def regen_one(name, src, inputs, tmpdir):
    out = os.path.join(tmpdir, name + ".b3.txt")
    srcp = source_path(src, tmpdir)
    args = [PY, GLASS, "prove", "--emit", out, srcp] + [f"{k}={v}" for k, v in inputs.items()]
    r = subprocess.run(args, capture_output=True, text=True, cwd=ROOT, timeout=PROVE_TIMEOUT)
    if r.returncode != 0 or not os.path.exists(out):
        raise RuntimeError(f"{name}: emit FAILED (rc={r.returncode})\n{r.stdout[-400:]}\n{r.stderr[-400:]}")
    ntok = len(open(out).read().split())
    # The independent verifier MUST accept before we trust the fixture.
    v = subprocess.run([PY, GLASS, "verify", out], capture_output=True, text=True, cwd=ROOT, timeout=PROVE_TIMEOUT)
    if "ACCEPT" not in v.stdout:
        raise RuntimeError(f"{name}: Pentecost did NOT ACCEPT the freshly emitted proof — refusing to write fixture.\n{v.stdout[-400:]}\n{v.stderr[-400:]}")
    dest = os.path.join(CORPUS, name + ".b3.txt.gz")
    old = os.path.getsize(dest) if os.path.exists(dest) else 0
    with open(out, "rb") as fi, gzip.open(dest, "wb") as fo:
        fo.write(fi.read())
    new = os.path.getsize(dest)
    print(f"  OK  {name:24s} {ntok:>9,d} tokens  gz {old:>9,d} -> {new:>9,d} bytes  (Pentecost ACCEPT)")


def main():
    with tempfile.TemporaryDirectory() as tmpdir:
        for name, src, inputs in SHAPES:
            regen_one(name, src, inputs, tmpdir)
    print(f"REGEN: {len(SHAPES)} fixtures regenerated + Pentecost-verified.")


if __name__ == "__main__":
    main()
